name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller (GUI)
        shell: cmd
        run: |
          REM Adjust --add-data pairs to include any non-Python files your app needs.
          python -m PyInstaller --noconfirm --clean --windowed --onefile ^
            --add-data "templates;templates" ^
            --add-data "PLV LOGO.png;." ^
            --hidden-import win32timezone ^
            --hidden-import pythoncom ^
            --hidden-import pywintypes ^
            --hidden-import win32com.client ^
            --name dynamic_payroll_gui dynamic_payroll_gui.py

      - name: Bundle templates and data
        shell: cmd
        run: |
          if exist dist\templates (
            rmdir /S /Q dist\templates
          )
          if exist templates (
            xcopy templates dist\templates /E /I /Y >NUL
          ) else (
            if exist "Template Payslip.xlsx" (
              if not exist dist\templates mkdir dist\templates
              copy /Y "Template Payslip.xlsx" dist\templates\ >NUL
            )
          )
          if exist emails.csv copy /Y emails.csv dist\ >NUL
          if exist emails\emails.csv copy /Y emails\emails.csv dist\ >NUL

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: dynamic_payroll_exe
          path: dist/**

